- id: validate_copyright
  name: validate_copyright
  description: "Validate Copyright"
  entry: validate_copyright
  files: '\.(js|ts|py|md)$'
  language: python
- id: clean_customized_doctypes
  name: clean_customized_doctypes
  description: "Clean customized doctypes"
  entry: clean_customized_doctypes
  language: python
  require_serial: true