- id: validate_copyright
  name: validate_copyright
  description: "Validate Copyright"
  entry: validate_copyright
  files: '\.(js|ts|py|md)$'
  language: python
- id: validate_javascript_dependencies
  name: validate_javascript_dependencies
  description: "Examine package.json across the installed apps on the site to detect any version mismatches"
  entry: validate_javascript_dependencies
  language: python
  require_serial: true